In [3]:
import numpy as np
from IPython.display import Audio
Fs = 11025
    
def normalize(dat):
    return 0.99 * dat / np.max(np.abs(dat))

def load_data():
    mix = np.loadtxt('q4data/q4.dat')
    return mix

def unmixer(X):
    M, N = X.shape
    W = np.eye(N)  #shape of W=5x5 , s=W*x  where =>x-(5,1) and s(5,1)

    anneal = [0.1, 0.1, 0.1, 0.05, 0.05, 0.05, 0.02, 0.02, 0.01, 0.01,
              0.005, 0.005, 0.002, 0.002, 0.001, 0.001]
    print('Separating tracks ...')
    ######## Your code here ##########

    
    for alpha in anneal:
      # Hint: you might want to use this alpha as learning rate for fast convergence
      # But feel free to use different learning rate. Training should be done in 3 minutes
      
      #calculate gradient
          for i in range(M): 
              x=X[i].reshape(-1,1)
              W_x=1-(2*g(np.dot(W,x)))
              W+=alpha*(np.dot(W_x,x.T)+np.linalg.inv(W.T))
      
    ###################################
    return W

def unmix(X, W):
    S = np.zeros(X.shape)
    ######### Your code here ##########
    S=np.dot(X,W.T)
    ##################################
    return S

def g(x):
    return (1/(1+np.exp(-x)))


In [4]:
X = normalize(load_data())



print('Playing mixed track 1')
Audio(X[:, 0], rate=Fs)



Playing mixed track 1


In [5]:
%time W = unmixer(X) # This will take about 1~2 minutes
S = normalize(unmix(X, W))
print(W)

Separating tracks ...
Wall time: 27 s
[[ 72.15081922  28.62441682  25.91040458 -17.2322227  -21.191357  ]
 [ 13.45886116  31.94398247  -4.03003982 -24.0095722   11.89906179]
 [ 18.89688784  -7.80435173  28.71469558  18.14356811 -21.17474522]
 [ -6.0119837   -4.15743607  -1.01692289  13.87321073  -5.26252289]
 [ -8.74061186  22.55821897   9.61289023  14.73637074  45.28841827]]


In [52]:
Audio(S[:, 0], rate=Fs) # instruction for download: click the vertical dots below and select "download"


In [61]:
Audio(S[:, 1], rate=Fs)

In [62]:
Audio(S[:, 2], rate=Fs)

In [63]:
Audio(S[:, 3], rate=Fs)

In [64]:
Audio(S[:, 4], rate=Fs)